services:
  viodata:
    image: docker.pkg.github.com/ac3cloud/vioreport/vioreport-sy6:latest
    environment:
      location: "sy6"
    restart: unless-stopped
    network_mode: "host"
    container_name: "viodata-sy6"
    volumes:
      - /mnt/data:/var/data
      - /mnt/dcj:/root/vir/dcj
